name: Test and Publish Package

on:
  push:
    branches:
      - master
      - release

  pull_request:
    branches: ['*']
      # - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_PASSWORD: 123456789
          MYSQL_ROOT_PASSWORD: 123456789
          MYSQL_DATABASE: db_tests
          MYSQL_USER: my_user
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          #  Maps tcp port 3306 on service container to the host
          - 3306:3306
    steps:
      - name: Install and Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:db

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: cd lib && npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     