name: Test and Publish Package

on:
  push:
    branches:
      - master
      # - release

  pull_request:
    branches:
      - master
      # - release

jobs:
  test:
    name: Test
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        node-version: [16.x]
        os: [ubuntu-latest]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_PASSWORD: 123456789
          MYSQL_ROOT_PASSWORD: 123456789
          MYSQL_DATABASE: db_tests
          MYSQL_USER: my_user
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          # Maps tcp port 3306 on service container to the host
          - 3306:3306


    steps:
      - name: Install and Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # node-version: 16
          node-version: ${{ matrix.node-version }}
        id: node
      
      - name: Checkout code
        uses: actions/checkout@v3 
      
      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:db
